package br.com.facility.enums;

public enum TipoLogradouro {

	//Do site do Correio, segundo fontes
	OUTROS, AEROPORTO, ALAMEDA, ÁREA, AVENIDA, CAMPO, CHÁCARA, COLÔNIA, CONDOMÍNIO, CONJUNTO, DISTRITO, ESPLANADA, ESTÇÃO, ESTRADA, FAVELA, FAZENDA, FEIRA, JARDIM, LADEIRA, LAGO, LAGOA, LARGO, LOTEAMENTO, MORRO, NÚCLEO, PARQUE, PASSARELA, PÁTIO, PRAÇA, QUADRA, RECANTO, RESIDENCIAL, RODOVIA, RUA, SETOR, SÍTIO, TRAVESSA, TRECHO, TREVO, VALE, VEREDA, VIA, VIADUTO, VIELA, VILA
	
}
